// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB2hnfwqMGrfy3j-np_v1WgLxvwN0xdic',
    appId: '1:456372333275:web:24ab1ff43233ac6463bafe',
    messagingSenderId: '456372333275',
    projectId: 'grocery-flutter-app-31baf',
    authDomain: 'grocery-flutter-app-31baf.firebaseapp.com',
    storageBucket: 'grocery-flutter-app-31baf.appspot.com',
    measurementId: 'G-ZMCNB15SMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApuifOQ49hN8Brk1QMM-DStlGI2uhezNs',
    appId: '1:456372333275:android:16e3ccbeb8088dd963bafe',
    messagingSenderId: '456372333275',
    projectId: 'grocery-flutter-app-31baf',
    storageBucket: 'grocery-flutter-app-31baf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCstQkc_6do6GeV1sw2NgKROaT2FgZ7Irg',
    appId: '1:456372333275:ios:24aa231a95173ef363bafe',
    messagingSenderId: '456372333275',
    projectId: 'grocery-flutter-app-31baf',
    storageBucket: 'grocery-flutter-app-31baf.appspot.com',
    iosClientId: '456372333275-6ru4ouqvsbpvaj4oieg2bmibassedca3.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCstQkc_6do6GeV1sw2NgKROaT2FgZ7Irg',
    appId: '1:456372333275:ios:24aa231a95173ef363bafe',
    messagingSenderId: '456372333275',
    projectId: 'grocery-flutter-app-31baf',
    storageBucket: 'grocery-flutter-app-31baf.appspot.com',
    iosClientId: '456372333275-6ru4ouqvsbpvaj4oieg2bmibassedca3.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );
}
